### ISSUE TITLE
Modular approach?

### ISSUE THREAD

**Issue by dodekeract** [dotModded/ContinuumShader#2]
I'm not a GLSL programmer, so would it be practically possible to build this as a modular system? As I already offered on facebook I'd be able to make a build tool/script/web-application which would only include the features desired by the end user.

**Comment by dotModded** [comment]
So it is possible to an extent, if you would like to work on something like this feel free. If it works well I'd love to see it in action. If we did each feature as a define you add to specific files and can compress it then great.

**Comment by dodekeract** [comment]
I did [something similar for Dota 2 configuration files](https://manta.dodekeract.report). Only difference is that this time I'd need some help to know what's actually needed for which feature. I understand the basics of GLSL, but that's about it. If it's "clear" where everything belongs I'm most certainly able to commit [some generator code](https://github.com/dodekeract/manta-config-engine).

**Comment by dodekeract** [comment]
Could we setup some sort of chat, so that I'm able to talk about implementation details with either one of you? I think github issues are to "slow" for discussing stuff like that. I'd suggest Jabber/XMPP or https://discord.gg. If nothing else is possible I'd agree to using facebook chat for the initial discussion, but I strongly prefer about anything else.

**Comment by dotModded** [comment]
We have a slack for developers and we always respond to FB, if you are looking to actively work on the shader we can invite you into the slack chat, send us a pm on fb with your name and email

**Comment by dodekeract** [comment]
Since optifine/shadersmod made this available ingame I will close this.
